version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db_video_analytics
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: ErpUser123.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql  # автоматически создаст таблицы при первом запуске
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: video_analytics_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # Если нужно загрузить данные при старте (один раз):
    # command: sh -c "sleep 10 && python load_data.py && python bot.py"

volumes:
  postgres_data: